import type { GitState } from "../schema/index.js";
import {
  parseDecisions,
  parseFailures,
  stripTemplate,
  type HandoffInput,
  type ParsedMarkdown,
  type Decision,
  type Failure,
} from "../core/handoff.js";

const NOT_RECORDED = "(not recorded)";

/**
 * Renders a self-contained Markdown handoff for the next coding agent.
 * Pure and deterministic: identical `.ctxpack/` input always produces identical output.
 */
export function renderGenericHandoff(input: HandoffInput): string {
  const { manifest, state } = input.pack;
  const { markdown } = input;
  const blocks: string[] = [];

  blocks.push(
    `# Handoff: ${manifest.project}\n\n` +
      `> Generated by \`ctxpack handoff\` (ctxpack ${manifest.version}, schema v${manifest.schemaVersion}).\n` +
      `> Pack last updated: ${manifest.updatedAt}. Git data below reflects the last \`ctxpack capture\`, not a live read.`,
  );

  const projectNotes = markdown.project === undefined ? [] : stripTemplate(markdown.project, "project");
  if (projectNotes.length > 0) {
    blocks.push(["## Project Notes", "", ...projectNotes].join("\n"));
  }

  blocks.push(
    ["## Current Goal", "", state.goal.trim() || `${NOT_RECORDED} — .ctxpack/state.json has no goal.`].join("\n"),
  );

  blocks.push(
    [
      "## Current State",
      "",
      `Status: ${state.status.toUpperCase()}`,
      "",
      "Completed:",
      ...list(state.completed),
      "",
      "In progress:",
      ...list(state.currentTasks),
    ].join("\n"),
  );

  blocks.push(renderDecisions(markdown.decisions).join("\n"));
  blocks.push(renderFailures(markdown.failures).join("\n"));
  blocks.push(["## Current Blockers", "", ...list(state.blockers)].join("\n"));
  blocks.push(["## Next Actions", "", ...numbered(state.nextActions)].join("\n"));
  blocks.push(["## Relevant Files", "", ...list(state.relevantFiles)].join("\n"));
  blocks.push(["## Verification", "", ...verification(state.verification)].join("\n"));
  blocks.push(renderGit(state.git).join("\n"));

  return blocks.join("\n\n") + "\n";
}

function renderDecisions(text: string | undefined): string[] {
  const heading = "## Important Decisions";
  if (text === undefined) return [heading, "", `${NOT_RECORDED} — no decisions.md in .ctxpack/.`];
  const parsed: ParsedMarkdown<Decision> = parseDecisions(text);
  const lines: string[] = [heading, ""];
  if (parsed.entries.length === 0 && parsed.notes.length === 0) {
    lines.push(`${NOT_RECORDED} — decisions.md has no entries yet.`);
    return lines;
  }
  for (const d of parsed.entries) {
    lines.push(`- ${d.date}: ${d.summary}`);
    if (d.reason) lines.push(`  Reason: ${d.reason}`);
  }
  appendNotes(lines, parsed.notes);
  return lines;
}

function renderFailures(text: string | undefined): string[] {
  const heading = "## Known Failed Approaches";
  if (text === undefined) return [heading, "", `${NOT_RECORDED} — no failures.md in .ctxpack/.`];
  const parsed: ParsedMarkdown<Failure> = parseFailures(text);
  const lines: string[] = [heading, ""];
  if (parsed.entries.length === 0 && parsed.notes.length === 0) {
    lines.push(`${NOT_RECORDED} — failures.md has no entries yet.`);
    return lines;
  }
  for (const f of parsed.entries) {
    lines.push(`- ${f.approach}: ${f.result}`);
    if (f.reason) lines.push(`  Reason: ${f.reason}`);
  }
  appendNotes(lines, parsed.notes);
  return lines;
}

function appendNotes(lines: string[], notes: string[]): void {
  if (notes.length === 0) return;
  lines.push("", "Also recorded (verbatim):", "");
  lines.push(...notes);
}

function renderGit(git: GitState): string[] {
  const heading = "## Git State (last capture)";
  const lines: string[] = [heading, ""];
  if (git.headState === undefined && git.branch === undefined && git.head === undefined) {
    lines.push(`${NOT_RECORDED} — \`ctxpack capture\` has not run yet.`);
    return lines;
  }
  if (git.branch !== undefined) lines.push(`Branch: ${git.branch}`);
  if (git.headState !== undefined) lines.push(`HEAD state: ${git.headState}`);
  if (git.head !== undefined) lines.push(`HEAD: ${git.head}`);
  if (git.clean !== undefined) lines.push(`Clean: ${git.clean ? "yes" : "no"}`);
  if (git.stat !== undefined) {
    const { staged, unstaged } = git.stat;
    lines.push(`Staged: ${staged.files} files (+${staged.insertions} -${staged.deletions})`);
    lines.push(`Unstaged: ${unstaged.files} files (+${unstaged.insertions} -${unstaged.deletions})`);
  }
  if (git.changedFiles !== undefined) {
    lines.push("", `Changed files (${git.changedFiles.length}):`);
    lines.push(...list(git.changedFiles));
  }
  if (git.recentCommits !== undefined && git.recentCommits.length > 0) {
    lines.push("", "Recent commits:");
    for (const c of git.recentCommits) lines.push(`- ${c.shortSha} ${c.subject} (${c.author}, ${c.date})`);
  }
  return lines;
}

function list(items: string[]): string[] {
  if (items.length === 0) return [NOT_RECORDED];
  return items.map((item) => `- ${item}`);
}

function numbered(items: string[]): string[] {
  if (items.length === 0) return [NOT_RECORDED];
  return items.map((item, i) => `${i + 1}. ${item}`);
}

function verification(items: { name: string; result: string; detail?: string | undefined }[]): string[] {
  if (items.length === 0) return [NOT_RECORDED];
  return items.map((v) => `- ${v.name}: ${v.result.toUpperCase()}${v.detail ? ` (${v.detail})` : ""}`);
}
