import {
  NOT_RECORDED,
  bullets,
  buildView,
  commitLines,
  gitFacts,
  hasGitCapture,
  isSectionEmpty,
  numbered,
  verificationLine,
  type HandoffView,
} from "./view.js";
import type { HandoffInput } from "../core/handoff.js";

/**
 * Renders a self-contained Markdown handoff for the next coding agent.
 * Pure and deterministic: identical `.ctxpack/` input always produces identical output.
 */
export function renderGenericHandoff(input: HandoffInput): string {
  const view = buildView(input);
  const blocks: string[] = [];

  blocks.push(
    `# Handoff: ${view.manifest.project}\n\n` +
      `> Generated by \`ctxpack handoff\` (ctxpack ${view.manifest.version}, schema v${view.manifest.schemaVersion}).\n` +
      `> Pack last updated: ${view.manifest.updatedAt}. Git data below reflects the last \`ctxpack capture\`, not a live read.`,
  );

  if (view.projectNotes.length > 0) {
    blocks.push(["## Project Notes", "", ...view.projectNotes].join("\n"));
  }

  blocks.push(
    ["## Current Goal", "", view.goal || `${NOT_RECORDED} — .ctxpack/state.json has no goal.`].join("\n"),
  );

  blocks.push(
    [
      "## Current State",
      "",
      `Status: ${view.status.toUpperCase()}`,
      "",
      "Completed:",
      ...bullets(view.completed),
      "",
      "In progress:",
      ...bullets(view.currentTasks),
    ].join("\n"),
  );

  blocks.push(renderDecisions(view).join("\n"));
  blocks.push(renderFailures(view).join("\n"));
  blocks.push(["## Current Blockers", "", ...bullets(view.blockers)].join("\n"));
  blocks.push(["## Next Actions", "", ...numbered(view.nextActions)].join("\n"));
  blocks.push(["## Relevant Files", "", ...bullets(view.relevantFiles)].join("\n"));
  blocks.push(renderVerification(view).join("\n"));
  blocks.push(renderGit(view).join("\n"));

  return blocks.join("\n\n") + "\n";
}

function renderDecisions(view: HandoffView): string[] {
  const heading = "## Important Decisions";
  if (view.decisions.entries === undefined)
    return [heading, "", `${NOT_RECORDED} — no decisions.md in .ctxpack/.`];
  const lines: string[] = [heading, ""];
  if (isSectionEmpty(view.decisions)) {
    lines.push(`${NOT_RECORDED} — decisions.md has no entries yet.`);
    return lines;
  }
  for (const d of view.decisions.entries) {
    lines.push(`- ${d.date}: ${d.summary}`);
    if (d.reason) lines.push(`  Reason: ${d.reason}`);
  }
  appendNotes(lines, view.decisions.notes);
  return lines;
}

function renderFailures(view: HandoffView): string[] {
  const heading = "## Known Failed Approaches";
  if (view.failures.entries === undefined)
    return [heading, "", `${NOT_RECORDED} — no failures.md in .ctxpack/.`];
  const lines: string[] = [heading, ""];
  if (isSectionEmpty(view.failures)) {
    lines.push(`${NOT_RECORDED} — failures.md has no entries yet.`);
    return lines;
  }
  for (const f of view.failures.entries) {
    lines.push(`- ${f.approach}: ${f.result}`);
    if (f.reason) lines.push(`  Reason: ${f.reason}`);
  }
  appendNotes(lines, view.failures.notes);
  return lines;
}

function appendNotes(lines: string[], notes: string[]): void {
  if (notes.length === 0) return;
  lines.push("", "Also recorded (verbatim):", "");
  lines.push(...notes);
}

function renderVerification(view: HandoffView): string[] {
  const lines = ["## Verification", ""];
  if (view.verification.length === 0) lines.push(NOT_RECORDED);
  else lines.push(...view.verification.map((v) => `- ${verificationLine(v)}`));
  return lines;
}

function renderGit(view: HandoffView): string[] {
  const heading = "## Git State (last capture)";
  const lines: string[] = [heading, ""];
  if (!hasGitCapture(view.git)) {
    lines.push(`${NOT_RECORDED} — \`ctxpack capture\` has not run yet.`);
    return lines;
  }
  lines.push(...gitFacts(view.git));
  if (view.git.changedFiles !== undefined) {
    lines.push("", `Changed files (${view.git.changedFiles.length}):`);
    lines.push(...bullets(view.git.changedFiles));
  }
  lines.push(...(view.git.recentCommits !== undefined && view.git.recentCommits.length > 0 ? ["", "Recent commits:"] : []));
  lines.push(...commitLines(view.git));
  return lines;
}
